In [3]:
!pip install numpy

In [4]:
import numpy as np

In [5]:
age = np.array([12,13,14,15])
print(age)

[12 13 14 15]


In [6]:
type(age)

numpy.ndarray

In [7]:
ar1 = np.array([[6,3,2],[3,2,3],[5,4,1]])
ar2 = np.array([[1,3,3],[7,4,5],[1,3,1]])
print(ar1)
print(ar2)

[[6 3 2]
 [3 2 3]
 [5 4 1]]
[[1 3 3]
 [7 4 5]
 [1 3 1]]


In [8]:
ar1.shape


(3, 3)

In [9]:
ar1.ndim

2

In [10]:
ar1.size

9

In [11]:
ar1.sum()

np.int64(29)

In [12]:
ar1.mean()

np.float64(3.2222222222222223)

In [13]:
ar1.std()

np.float64(1.4740554623801778)

In [14]:
ar1.var()

np.float64(2.17283950617284)

In [15]:
#Row wise sum
np.sum(ar1,axis = 0)

array([14,  9,  6])

In [16]:
#column wise sum
np.sum(ar1,axis = 1)


array([11,  8, 10])

In [17]:
np.sqrt(ar1)

array([[2.44948974, 1.73205081, 1.41421356],
       [1.73205081, 1.41421356, 1.73205081],
       [2.23606798, 2.        , 1.        ]])

In [18]:
np.exp(ar1)

array([[403.42879349,  20.08553692,   7.3890561 ],
       [ 20.08553692,   7.3890561 ,  20.08553692],
       [148.4131591 ,  54.59815003,   2.71828183]])

In [19]:
np.log(ar1)

array([[1.79175947, 1.09861229, 0.69314718],
       [1.09861229, 0.69314718, 1.09861229],
       [1.60943791, 1.38629436, 0.        ]])

In [20]:
np.log

<ufunc 'log'>

In [21]:
#Transpose of a matrix
ar1.T

array([[6, 3, 5],
       [3, 2, 4],
       [2, 3, 1]])

In [22]:
ar1 + ar2

array([[ 7,  6,  5],
       [10,  6,  8],
       [ 6,  7,  2]])

In [23]:
ar1-ar2

array([[ 5,  0, -1],
       [-4, -2, -2],
       [ 4,  1,  0]])

In [24]:
ar1*ar2

array([[ 6,  9,  6],
       [21,  8, 15],
       [ 5, 12,  1]])

In [25]:
ar1.dot(ar2)

array([[29, 36, 35],
       [20, 26, 22],
       [34, 34, 36]])

In [26]:
5*ar1

array([[30, 15, 10],
       [15, 10, 15],
       [25, 20,  5]])

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
#Identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
#Both identity and eye functions can be used to create an identity matrix. The difference is that the eye function allows you to specify the number of rows and columns, while the identity function creates a square matrix of a specified size.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
np.eye(4, k = 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [34]:
ar3 = np.array([5,9,11,13,16,14,15,17,16,18,19,20])
print(ar3)

[ 5  9 11 13 16 14 15 17 16 18 19 20]


In [35]:
ar3.shape
print(ar3)

[ 5  9 11 13 16 14 15 17 16 18 19 20]


In [36]:
ar2.ndim
print(ar2)

[[1 3 3]
 [7 4 5]
 [1 3 1]]


In [37]:
ar3.size
print(ar3)

[ 5  9 11 13 16 14 15 17 16 18 19 20]


In [38]:
ar4 = ar3.reshape(3,4)
print(ar4)

[[ 5  9 11 13]
 [16 14 15 17]
 [16 18 19 20]]


In [39]:
ar4 = ar3.reshape(3,2,2)
print(ar4)

[[[ 5  9]
  [11 13]]

 [[16 14]
  [15 17]]

 [[16 18]
  [19 20]]]


In [40]:
ar5 = np.random.randint(3,7,15)
print(ar5)

[6 4 4 3 6 6 4 6 4 4 3 4 4 5 3]


In [41]:
ar5 = np.random.randint(3,7,15).reshape(3,5)
print(ar5)

[[3 3 4 6 3]
 [5 4 4 6 4]
 [4 3 4 6 6]]


In [42]:
ar6 = np.arange(3,20,4)
print(ar6)

[ 3  7 11 15 19]


In [43]:
ar6 = np.arange(3,80,4)
print(ar6)

[ 3  7 11 15 19 23 27 31 35 39 43 47 51 55 59 63 67 71 75 79]


In [44]:
ar6 = np.arange(3,10,10)
print(ar6)

[3]


In [45]:
ar7 = np.linspace(2,52,3)
print(ar7)


[ 2. 27. 52.]


In [46]:
#In linspace, the third parameter specifies the number of evenly spaced values to generate between the start and end values. In this case, it generates 8 values between 2 and 20, which are 2, 4, 6, 8, 10, 12, 14, and 16.
ar7 = np.linspace(2,20,8)
print(ar7)

[ 2.          4.57142857  7.14285714  9.71428571 12.28571429 14.85714286
 17.42857143 20.        ]


In [47]:
ar7 = np.linspace(2,80,5)
print(ar7)

[ 2.  21.5 41.  60.5 80. ]


In [48]:
array1 = np.array([7,8,9,10,12,15])
array2 = np.array([6,3,9,4,12,15])
print(array1)
print(array2)
#np.where() function is used to return the indices of elements in an input array that satisfy a given condition. In this case, it will return the indices where the elements of array1 are equal to the corresponding elements of array2.   
np.where(array1 == array2)

[ 7  8  9 10 12 15]
[ 6  3  9  4 12 15]


(array([2, 4, 5]),)

In [49]:
7/2

3.5

In [50]:
7%2

1

In [51]:
8%4

0

In [52]:
9%2

1

In [53]:
array1%2 == 1

array([ True, False,  True, False, False,  True])

In [54]:
array1[array1%2 == 1]

array([ 7,  9, 15])

In [55]:
array1[array1>10]

array([12, 15])

In [56]:
array1[array1%2 ==1 ] = -1
print(array1)

[-1  8 -1 10 12 -1]


In [58]:
#Week2 Workshop Starts From Here
Array1 = np.array([1,2,3,4,5,6,7,8,9,10])
Array2 = np.array([11,12,13,14,15,16,17,18,19,20])
Array1 + Array2


array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [61]:
arr1 = np.array([[1, 2], [3, 4]])
scalar = arr1 * 10
print(scalar)

[[10 20]
 [30 40]]


In [62]:
identity_mat = np.eye(3)

In [64]:
Array1 = np.arange(8) 
Array1 = Array1.reshape((2, 2, 2))
print(Array1)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [65]:
Array1.astype(float)

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [70]:
exercise_1 = np.array([0,1,2,3,4,5,6,7,8,9])
exercise_1[exercise_1%2 == 1] = -1
print(exercise_1)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [79]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,8,5,6])
print(a)
print(b)
np.where(a == b)

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  8  5  6]


(array([1, 3, 5, 8, 9]),)

In [ ]:
|