In [118]:
!pip install numpy

In [119]:
import numpy as np

In [120]:
age = np.array([12,13,14,15])
print(age)

[12 13 14 15]


In [121]:
type(age)

numpy.ndarray

In [122]:
ar1 = np.array([[6,3,2],[3,2,3],[5,4,1]])
ar2 = np.array([[1,3,3],[7,4,5],[1,3,1]])
print(ar1)
print(ar2)

[[6 3 2]
 [3 2 3]
 [5 4 1]]
[[1 3 3]
 [7 4 5]
 [1 3 1]]


In [123]:
ar1.shape


(3, 3)

In [124]:
ar1.ndim

2

In [125]:
ar1.size

9

In [126]:
ar1.sum()

np.int64(29)

In [127]:
ar1.mean()

np.float64(3.2222222222222223)

In [128]:
ar1.std()

np.float64(1.4740554623801778)

In [129]:
ar1.var()

np.float64(2.17283950617284)

In [130]:
#Row wise sum
np.sum(ar1,axis = 0)

array([14,  9,  6])

In [131]:
#column wise sum
np.sum(ar1,axis = 1)


array([11,  8, 10])

In [132]:
np.sqrt(ar1)

array([[2.44948974, 1.73205081, 1.41421356],
       [1.73205081, 1.41421356, 1.73205081],
       [2.23606798, 2.        , 1.        ]])

In [133]:
np.exp(ar1)

array([[403.42879349,  20.08553692,   7.3890561 ],
       [ 20.08553692,   7.3890561 ,  20.08553692],
       [148.4131591 ,  54.59815003,   2.71828183]])

In [134]:
np.log(ar1)

array([[1.79175947, 1.09861229, 0.69314718],
       [1.09861229, 0.69314718, 1.09861229],
       [1.60943791, 1.38629436, 0.        ]])

In [135]:
np.log

<ufunc 'log'>

In [136]:
#Transpose of a matrix
ar1.T

array([[6, 3, 5],
       [3, 2, 4],
       [2, 3, 1]])

In [137]:
ar1 + ar2

array([[ 7,  6,  5],
       [10,  6,  8],
       [ 6,  7,  2]])

In [138]:
ar1-ar2

array([[ 5,  0, -1],
       [-4, -2, -2],
       [ 4,  1,  0]])

In [139]:
ar1*ar2

array([[ 6,  9,  6],
       [21,  8, 15],
       [ 5, 12,  1]])

In [140]:
ar1.dot(ar2)

array([[29, 36, 35],
       [20, 26, 22],
       [34, 34, 36]])

In [141]:
5*ar1

array([[30, 15, 10],
       [15, 10, 15],
       [25, 20,  5]])

In [142]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [143]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [144]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [145]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [146]:
#Identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [147]:
#Both identity and eye functions can be used to create an identity matrix. The difference is that the eye function allows you to specify the number of rows and columns, while the identity function creates a square matrix of a specified size.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [148]:
np.eye(4, k = 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [149]:
ar3 = np.array([5,9,11,13,16,14,15,17,16,18,19,20])
print(ar3)

[ 5  9 11 13 16 14 15 17 16 18 19 20]


In [150]:
ar3.shape
print(ar3)

[ 5  9 11 13 16 14 15 17 16 18 19 20]


In [151]:
ar2.ndim
print(ar2)

[[1 3 3]
 [7 4 5]
 [1 3 1]]


In [152]:
ar3.size
print(ar3)

[ 5  9 11 13 16 14 15 17 16 18 19 20]


In [153]:
ar4 = ar3.reshape(3,4)
print(ar4)

[[ 5  9 11 13]
 [16 14 15 17]
 [16 18 19 20]]


In [154]:
ar4 = ar3.reshape(3,2,2)
print(ar4)

[[[ 5  9]
  [11 13]]

 [[16 14]
  [15 17]]

 [[16 18]
  [19 20]]]


In [155]:
ar5 = np.random.randint(3,7,15)
print(ar5)

[4 6 6 3 4 3 5 6 4 4 6 6 3 4 5]


In [156]:
ar5 = np.random.randint(3,7,15).reshape(3,5)
print(ar5)

[[5 4 4 3 5]
 [4 6 6 3 3]
 [4 4 3 3 4]]


In [157]:
ar6 = np.arange(3,20,4)
print(ar6)

[ 3  7 11 15 19]


In [158]:
ar6 = np.arange(3,80,4)
print(ar6)

[ 3  7 11 15 19 23 27 31 35 39 43 47 51 55 59 63 67 71 75 79]


In [159]:
ar6 = np.arange(3,10,10)
print(ar6)

[3]


In [160]:
ar7 = np.linspace(2,52,3)
print(ar7)


[ 2. 27. 52.]


In [161]:
#In linspace, the third parameter specifies the number of evenly spaced values to generate between the start and end values. In this case, it generates 8 values between 2 and 20, which are 2, 4, 6, 8, 10, 12, 14, and 16.
ar7 = np.linspace(2,20,8)
print(ar7)

[ 2.          4.57142857  7.14285714  9.71428571 12.28571429 14.85714286
 17.42857143 20.        ]


In [162]:
ar7 = np.linspace(2,80,5)
print(ar7)

[ 2.  21.5 41.  60.5 80. ]


In [163]:
array1 = np.array([7,8,9,10,12,15])
array2 = np.array([6,3,9,4,12,15])
print(array1)
print(array2)
#np.where() function is used to return the indices of elements in an input array that satisfy a given condition. In this case, it will return the indices where the elements of array1 are equal to the corresponding elements of array2.   
np.where(array1 == array2)

[ 7  8  9 10 12 15]
[ 6  3  9  4 12 15]


(array([2, 4, 5]),)

In [164]:
7/2

3.5

In [165]:
7%2

1

In [166]:
8%4

0

In [167]:
9%2

1

In [168]:
array1%2 == 1

array([ True, False,  True, False, False,  True])

In [169]:
array1[array1%2 == 1]

array([ 7,  9, 15])

In [170]:
array1[array1>10]

array([12, 15])

In [171]:
array1[array1%2 ==1 ] = -1
print(array1)

[-1  8 -1 10 12 -1]


In [172]:
#Week2 Workshop Starts From Here
Array1 = np.array([1,2,3,4,5,6,7,8,9,10])
Array2 = np.array([11,12,13,14,15,16,17,18,19,20])
Array1 + Array2


array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [173]:
arr1 = np.array([[1, 2], [3, 4]])
scalar = arr1 * 10
print(scalar)

[[10 20]
 [30 40]]


In [174]:
identity_mat = np.eye(3)

In [175]:
Array1 = np.arange(8) 
Array1 = Array1.reshape((2, 2, 2))
print(Array1)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [176]:
Array1.astype(float)

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [177]:
exercise_1 = np.array([0,1,2,3,4,5,6,7,8,9])
exercise_1[exercise_1%2 == 1] = -1
print(exercise_1)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [178]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,8,5,6])
print(a)
print(b)
np.where(a == b)

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  8  5  6]


(array([1, 3, 5, 8, 9]),)

In [179]:
myArray = np.random.randint(10,50,(4,4))
print(myArray)

[[19 19 45 10]
 [41 47 18 11]
 [38 10 33 33]
 [40 16 19 45]]


In [180]:
myArray[1,2]

np.int64(18)

In [181]:
myArray[0:2,0:4]

array([[19, 19, 45, 10],
       [41, 47, 18, 11]])

In [182]:
myArray = [[0:2], : ]

SyntaxError: invalid syntax (1056686407.py, line 1)

In [ ]:
myArray = [: ,[0,1]]

SyntaxError: invalid syntax (1981520015.py, line 1)

In [ ]:
myArray = [:,[2:4]]

SyntaxError: invalid syntax (1021922995.py, line 1)

In [ ]:
myArray = [0:2,0:2]

SyntaxError: invalid syntax (614372378.py, line 1)

In [ ]:
quarter1 = np.array([[200,220,250],[150,180,210],[300,330,360]])
quarter2 = np.array([[209,231,259],[155,192,222],[310,340,375]])
print(quarter1)
print(quarter2)

[[200 220 250]
 [150 180 210]
 [300 330 360]]
[[209 231 259]
 [155 192 222]
 [310 340 375]]


In [ ]:
total = quarter1 + quarter2
print(total)

[[409 451 509]
 [305 372 432]
 [610 670 735]]


In [ ]:
np.sum(total, axis = 0)

array([1324, 1493, 1676])

In [ ]:
np.sum(total, axis = 1)

array([1369, 1109, 2015])

In [ ]:
price = np.array([1200,900,1900])

In [ ]:
price.dot(price)

np.int64(5860000)

In [ ]:
SalesGrowth = quarter2 - quarter1
print(SalesGrowth)

[[ 9 11  9]
 [ 5 12 12]
 [10 10 15]]
