In [49]:
!pip install numpy

In [4]:
import numpy as np

In [5]:
arr1 = np.array([7,9,3,2,6])

In [6]:
print(arr1)

[7 9 3 2 6]


In [7]:
arr2 = np.array([[3,7,4],[1,2,6],[7,2,3]])
arr3 = np.array([[4,1,6],[9,7,6],[3,2,1]])
print(arr2)
print(arr3)

[[3 7 4]
 [1 2 6]
 [7 2 3]]
[[4 1 6]
 [9 7 6]
 [3 2 1]]


In [8]:
arr2+arr3

array([[ 7,  8, 10],
       [10,  9, 12],
       [10,  4,  4]])

In [9]:
arr2*arr3

array([[12,  7, 24],
       [ 9, 14, 36],
       [21,  4,  3]])

In [10]:
arr2*arr3

array([[12,  7, 24],
       [ 9, 14, 36],
       [21,  4,  3]])

In [11]:
arr2/arr3

array([[0.75      , 7.        , 0.66666667],
       [0.11111111, 0.28571429, 1.        ],
       [2.33333333, 1.        , 3.        ]])

In [12]:
5*arr2

array([[15, 35, 20],
       [ 5, 10, 30],
       [35, 10, 15]])

In [13]:
arr2.shape

(3, 3)

In [14]:
arr2.size

9

In [15]:
arr2.sum

<function ndarray.sum(axis=None, dtype=None, out=None, **kwargs)>

In [16]:
arr2.sum()

np.int64(35)

In [17]:
arr2.sum(axis=0)

array([11, 11, 13])

In [18]:
arr2.sum(axis=1)

array([14,  9, 12])

In [19]:
arr2.mean()

np.float64(3.888888888888889)

In [20]:
arr2.std()

np.float64(2.1314806770278754)

In [21]:
arr2.var()

np.float64(4.54320987654321)

In [22]:
arr2.ndim

2

In [23]:
np.exp(arr2)

array([[  20.08553692, 1096.63315843,   54.59815003],
       [   2.71828183,    7.3890561 ,  403.42879349],
       [1096.63315843,    7.3890561 ,   20.08553692]])

In [24]:
np.sqrt(arr2)

array([[1.73205081, 2.64575131, 2.        ],
       [1.        , 1.41421356, 2.44948974],
       [2.64575131, 1.41421356, 1.73205081]])

In [25]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [26]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [27]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [29]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
np.full((7,6),3)

array([[3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])

In [31]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
np.eye(4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [33]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
arr5 = np.array([7,6,5,4,3,2,1,8,9,10,11,12])

In [35]:
print(arr5)

[ 7  6  5  4  3  2  1  8  9 10 11 12]


In [36]:
arr5.reshape(3,4)

array([[ 7,  6,  5,  4],
       [ 3,  2,  1,  8],
       [ 9, 10, 11, 12]])

In [37]:
arr5.reshape(6,2)

array([[ 7,  6],
       [ 5,  4],
       [ 3,  2],
       [ 1,  8],
       [ 9, 10],
       [11, 12]])

In [38]:
arr5.reshape(3,2,2)

array([[[ 7,  6],
        [ 5,  4]],

       [[ 3,  2],
        [ 1,  8]],

       [[ 9, 10],
        [11, 12]]])

In [39]:
v = arr5.reshape(3,2,2)
v.ndim

3

In [40]:
v.astype(float)

array([[[ 7.,  6.],
        [ 5.,  4.]],

       [[ 3.,  2.],
        [ 1.,  8.]],

       [[ 9., 10.],
        [11., 12.]]])

In [41]:
a =np.array([1,3,7,9,8,16])
b =np.array([12,3,4,9,0,16])
print(a)
print(b)

[ 1  3  7  9  8 16]
[12  3  4  9  0 16]


In [42]:
np.where(a==b)

(array([1, 3, 5]),)

In [43]:
a%2

array([1, 1, 1, 1, 0, 0])

In [44]:
a%2 !=0

array([ True,  True,  True,  True, False, False])

In [45]:
a[a%2 !=0]

array([1, 3, 7, 9])

In [46]:
a[a%2 !=0] = -1
print(a)

[-1 -1 -1 -1  8 16]


In [47]:
np.random.randint(2,6,15)

array([2, 2, 5, 3, 2, 5, 2, 4, 3, 2, 5, 5, 2, 5, 4])

In [48]:
np.random.randint(2,6,15).reshape(3,5)

array([[3, 5, 3, 5, 4],
       [4, 5, 2, 3, 2],
       [4, 2, 5, 3, 5]])