In [99]:
question_one = [10,20,30,40,50]

In [100]:
print(question_one)

[10, 20, 30, 40, 50]


In [101]:
question_one.append(60)

In [102]:
print(question_one)

[10, 20, 30, 40, 50, 60]


In [103]:
question_one.remove(20)

In [104]:
print(question_one)

[10, 30, 40, 50, 60]


In [105]:
question_one.extend([70])

In [106]:
print(question_one)

[10, 30, 40, 50, 60, 70]


In [107]:
question_one.append([7,8,9])

In [108]:
print(question_one)

[10, 30, 40, 50, 60, 70, [7, 8, 9]]


In [109]:
del question_one[1]

In [110]:
question_one.extend([10,11,12])

In [111]:
print(question_one)

[10, 40, 50, 60, 70, [7, 8, 9], 10, 11, 12]


In [112]:
question_one.insert(1,15)

In [113]:
question_one.append(15)

In [114]:
question_one.remove(15)

In [115]:
print(question_one)

[10, 40, 50, 60, 70, [7, 8, 9], 10, 11, 12, 15]


In [116]:
my_list=[5,10,15,20,25,10,5,True]

In [117]:
print(my_list)

[5, 10, 15, 20, 25, 10, 5, True]


In [118]:
s = sum(my_list)

In [119]:
print("Sum", s)

Sum 91


In [120]:
my_tuple =(10,20,30,40,50,60,70,80)

In [121]:
print(my_tuple)

(10, 20, 30, 40, 50, 60, 70, 80)


In [122]:
print(my_tuple[-1])

80


In [123]:
print(my_tuple[2])

30


In [124]:
print(my_tuple[2:])

(30, 40, 50, 60, 70, 80)


In [125]:
print(my_tuple[:5])

(10, 20, 30, 40, 50)


In [126]:
print(my_tuple[2:5])

(30, 40, 50)


In [127]:
print(my_tuple[2:6:2])

(30, 50)


In [128]:
print(my_tuple[2:6:1])

(30, 40, 50, 60)


In [129]:
print(my_tuple[::])

(10, 20, 30, 40, 50, 60, 70, 80)


In [130]:
print(my_tuple[::-1])

(80, 70, 60, 50, 40, 30, 20, 10)


In [131]:
my_tuple1 = (10,20,30)

In [132]:
print(my_tuple1)

(10, 20, 30)


In [133]:
conv_list = list(my_tuple1)

In [134]:
print(conv_list)

[10, 20, 30]


In [135]:
conv_list.append(40)

In [136]:
print(conv_list)

[10, 20, 30, 40]


In [137]:
my_dict = {'Namd': 'Eijkeyal','Age':'20','city':'Lalitpur'}

In [138]:
print(my_dict)

{'Namd': 'Eijkeyal', 'Age': '20', 'city': 'Lalitpur'}


In [139]:
print(my_dict['Age'])

20


In [140]:
print(my_dict.get('Age'))

20


In [141]:
dict = {'a':10,'b':20}

In [142]:
print(dict)

{'a': 10, 'b': 20}


In [143]:
dict['c'] = 30

In [144]:
print(dict)

{'a': 10, 'b': 20, 'c': 30}


In [145]:
my_dict['Age']=21

In [146]:
print(my_dict)

{'Namd': 'Eijkeyal', 'Age': 21, 'city': 'Lalitpur'}


In [147]:
del my_dict['Age']

In [148]:
my_set = {1,2,3,4}

In [149]:
print(my_set)

{1, 2, 3, 4}


In [150]:
my_set.add(5)

In [151]:
set1 = {1,2,3}

In [152]:
set2 = {3,4,5}

In [153]:
isec = set1.intersection(set2)

In [154]:
print(isec)

{3}


In [155]:
uset = set1.union(set2)

In [156]:
print(uset)

{1, 2, 3, 4, 5}


In [157]:
diff = set1.difference(set2)

In [158]:
print(set1)

{1, 2, 3}


In [159]:
print(set2)

{3, 4, 5}


In [160]:
set1.intersection_update(set2)

In [161]:
print(set1)
print(set2)

{3}
{3, 4, 5}


In [162]:
set1.difference_update(set2)

In [163]:
print(set1)

set()


In [164]:
set1.difference_update(set2)

In [165]:
print(set1)

set()


In [166]:
s1 = {1,2,3,4}

In [167]:
s2 = {1,2}

In [168]:
s1.issuperset(s2)

True

In [169]:
s2.issuperset(s1)

False

In [170]:
2%2

0

In [171]:
1%2


1

In [172]:
for num in range(1,21):
    if(num%2==0):
        print(num,end=" ")

2 4 6 8 10 12 14 16 18 20 

In [173]:
!pip install numpy

In [174]:
import numpy as np

In [175]:
myArray = np.array([4,5,6,7])

In [176]:
print(myArray)

[4 5 6 7]


In [177]:
arr1 = np.array([[4,5,6],[1,2,3],[8,2,0]])

In [178]:
arr2 =np.array([[2,8,9],[8,3,7],[0,5,6]]) 

In [179]:
print(arr1)
print(arr2)

[[4 5 6]
 [1 2 3]
 [8 2 0]]
[[2 8 9]
 [8 3 7]
 [0 5 6]]


In [180]:
arr1.shape

(3, 3)

In [181]:
myArray.shape

(4,)

In [182]:
arr1.ndim

2

In [183]:
arr1.size

9

In [184]:
arr1 + arr2

array([[ 6, 13, 15],
       [ 9,  5, 10],
       [ 8,  7,  6]])

In [185]:
3*arr1

array([[12, 15, 18],
       [ 3,  6,  9],
       [24,  6,  0]])

In [186]:
arr1.dot(arr2)

array([[ 48,  77, 107],
       [ 18,  29,  41],
       [ 32,  70,  86]])

In [187]:
np.ones(4)

array([1., 1., 1., 1.])

In [188]:
np.zeros(3)

array([0., 0., 0.])

In [189]:
np.ones(shape = (4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [190]:
np.eye = (5,5)

In [191]:
myarray = np.array([4,5,6,7,12,11,4,5,6,8,9,10,11])

In [192]:
print(myarray)

[ 4  5  6  7 12 11  4  5  6  8  9 10 11]


In [193]:
myarray.shape

(13,)

In [194]:
myarray.ndim

1

In [196]:
arr = myarray.reshape(3,2,2)

ValueError: cannot reshape array of size 13 into shape (3,2,2)

In [ ]:
print(myarray.size) # This will show you the 13

13


In [ ]:
myarray[:12].reshape(3, 2, 2)

array([[[ 4,  5],
        [ 6,  7]],

       [[12, 11],
        [ 4,  5]],

       [[ 6,  8],
        [ 9, 10]]])

In [ ]:
myarray.reshape(13, 1, 1)

array([[[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[12]],

       [[11]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]]])

In [ ]:
myarray.ndim

1

In [ ]:
myarray.flatten()

array([ 4,  5,  6,  7, 12, 11,  4,  5,  6,  8,  9, 10, 11])

In [ ]:
np.random.randint(1,10,12).reshape(3,2,2)

array([[[6, 6],
        [6, 2]],

       [[6, 4],
        [3, 6]],

       [[7, 8],
        [3, 2]]])

In [ ]:
#This is the end of the week1 Numpy Excercise 