In [1]:
question_one = [10,20,30,40,50]

In [2]:
print(question_one)

[10, 20, 30, 40, 50]


In [3]:
question_one.append(60)

In [4]:
print(question_one)

[10, 20, 30, 40, 50, 60]


In [5]:
question_one.remove(20)

In [6]:
print(question_one)

[10, 30, 40, 50, 60]


In [7]:
question_one.extend([70])

In [8]:
print(question_one)

[10, 30, 40, 50, 60, 70]


In [9]:
question_one.append([7,8,9])

In [10]:
print(question_one)

[10, 30, 40, 50, 60, 70, [7, 8, 9]]


In [11]:
del question_one[1]

In [12]:
question_one.extend([10,11,12])

In [13]:
print(question_one)

[10, 40, 50, 60, 70, [7, 8, 9], 10, 11, 12]


In [14]:
question_one.insert(1,15)

In [15]:
question_one.append(15)

In [16]:
question_one.remove(15)

In [17]:
print(question_one)

[10, 40, 50, 60, 70, [7, 8, 9], 10, 11, 12, 15]


In [18]:
my_list=[5,10,15,20,25,10,5,True]

In [19]:
print(my_list)

[5, 10, 15, 20, 25, 10, 5, True]


In [20]:
s = sum(my_list)

In [21]:
print("Sum", s)

Sum 91


In [22]:
my_tuple =(10,20,30,40,50,60,70,80)

In [23]:
print(my_tuple)

(10, 20, 30, 40, 50, 60, 70, 80)


In [24]:
print(my_tuple[-1])

80


In [25]:
print(my_tuple[2])

30


In [26]:
print(my_tuple[2:])

(30, 40, 50, 60, 70, 80)


In [27]:
print(my_tuple[:5])

(10, 20, 30, 40, 50)


In [28]:
print(my_tuple[2:5])

(30, 40, 50)


In [29]:
print(my_tuple[2:6:2])

(30, 50)


In [30]:
print(my_tuple[2:6:1])

(30, 40, 50, 60)


In [31]:
print(my_tuple[::])

(10, 20, 30, 40, 50, 60, 70, 80)


In [32]:
print(my_tuple[::-1])

(80, 70, 60, 50, 40, 30, 20, 10)


In [33]:
my_tuple1 = (10,20,30)

In [34]:
print(my_tuple1)

(10, 20, 30)


In [35]:
conv_list = list(my_tuple1)

In [36]:
print(conv_list)

[10, 20, 30]


In [37]:
conv_list.append(40)

In [38]:
print(conv_list)

[10, 20, 30, 40]


In [39]:
my_dict = {'Namd': 'Eijkeyal','Age':'20','city':'Lalitpur'}

In [40]:
print(my_dict)

{'Namd': 'Eijkeyal', 'Age': '20', 'city': 'Lalitpur'}


In [41]:
print(my_dict['Age'])

20


In [42]:
print(my_dict.get('Age'))

20


In [43]:
dict = {'a':10,'b':20}

In [44]:
print(dict)

{'a': 10, 'b': 20}


In [45]:
dict['c'] = 30

In [46]:
print(dict)

{'a': 10, 'b': 20, 'c': 30}


In [47]:
my_dict['Age']=21

In [48]:
print(my_dict)

{'Namd': 'Eijkeyal', 'Age': 21, 'city': 'Lalitpur'}


In [49]:
del my_dict['Age']

In [50]:
my_set = {1,2,3,4}

In [51]:
print(my_set)

{1, 2, 3, 4}


In [52]:
my_set.add(5)

In [53]:
set1 = {1,2,3}

In [54]:
set2 = {3,4,5}

In [55]:
isec = set1.intersection(set2)

In [56]:
print(isec)

{3}


In [57]:
uset = set1.union(set2)

In [58]:
print(uset)

{1, 2, 3, 4, 5}


In [59]:
diff = set1.difference(set2)

In [60]:
print(set1)

{1, 2, 3}


In [61]:
print(set2)

{3, 4, 5}


In [62]:
set1.intersection_update(set2)

In [63]:
print(set1)
print(set2)

{3}
{3, 4, 5}


In [64]:
set1.difference_update(set2)

In [65]:
print(set1)

set()


In [66]:
set1.difference_update(set2)

In [67]:
print(set1)

set()


In [68]:
s1 = {1,2,3,4}

In [69]:
s2 = {1,2}

In [70]:
s1.issuperset(s2)

True

In [71]:
s2.issuperset(s1)

False

In [72]:
2%2

0

In [73]:
1%2


1

In [74]:
for num in range(1,21):
    if(num%2==0):
        print(num,end=" ")

2 4 6 8 10 12 14 16 18 20 

In [76]:
!pip install numpy

In [77]:
import numpy as np

In [78]:
myArray = np.array([4,5,6,7])

In [79]:
print(myArray)

[4 5 6 7]


In [80]:
arr1 = np.array([[4,5,6],[1,2,3],[8,2,0]])

In [81]:
arr2 =np.array([[2,8,9],[8,3,7],[0,5,6]]) 

In [82]:
print(arr1)
print(arr2)

[[4 5 6]
 [1 2 3]
 [8 2 0]]
[[2 8 9]
 [8 3 7]
 [0 5 6]]


In [83]:
arr1.shape

(3, 3)

In [84]:
myArray.shape

(4,)

In [85]:
arr1.ndim

2

In [87]:
arr1.size

9

In [88]:
arr1 + arr2

array([[ 6, 13, 15],
       [ 9,  5, 10],
       [ 8,  7,  6]])

In [89]:
3*arr1

array([[12, 15, 18],
       [ 3,  6,  9],
       [24,  6,  0]])

In [90]:
arr1.dot(arr2)

array([[ 48,  77, 107],
       [ 18,  29,  41],
       [ 32,  70,  86]])

In [91]:
np.ones(4)

array([1., 1., 1., 1.])

In [92]:
np.zeros(3)

array([0., 0., 0.])

In [93]:
np.ones(shape = (4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [95]:
np.eye = (5,5)

In [97]:
myarray = np.array([4,5,6,7,12,11,4,5,6,8,9,10,11])

In [99]:
print(myarray)

[ 4  5  6  7 12 11  4  5  6  8  9 10 11]


In [100]:
myarray.shape

(13,)

In [101]:
myarray.ndim

1

In [103]:
arr = myarray.reshape(3,2,2)

ValueError: cannot reshape array of size 13 into shape (3,2,2)

In [104]:
print(myarray.size) # This will show you the 13

13


In [105]:
myarray[:12].reshape(3, 2, 2)

array([[[ 4,  5],
        [ 6,  7]],

       [[12, 11],
        [ 4,  5]],

       [[ 6,  8],
        [ 9, 10]]])

In [106]:
myarray.reshape(13, 1, 1)

array([[[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[12]],

       [[11]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]]])

In [109]:
myarray.ndim

1

In [113]:
myarray.flatten()

array([ 4,  5,  6,  7, 12, 11,  4,  5,  6,  8,  9, 10, 11])

In [114]:
np.random.randint(1,10,12).reshape(3,2,2)

array([[[6, 6],
        [6, 2]],

       [[6, 4],
        [3, 6]],

       [[7, 8],
        [3, 2]]])

In [ ]:
#This is the end of the week1 Numpy Excercise 